# Setup
title:               Harry's List
tagline:             'Architect the future'
description:         'A blog by <a href="https://harrisonpowers.com" target="_blank">Harrison Powers</a>.'
url:                 http://blog.harrisonpowers.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Harrison Powers
  url:               https://harrisonpowers.com
  email:             harrisonpowers@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
